resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging

images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: placeholder
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: placeholder
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: placeholder
