apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    repository: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard/tree/main/cos-fleetshard-operator-debezium
    olm.skipRange: '>=1.1.6 <1.1.20'
  name: cos-fleetshard-operator-debezium.v1.1.20
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The cos-fleetshard-operator-debezium is responsible for managing Debezium connectors.
  displayName: cos-fleetshard-operator-debezium
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - cos.bf2.org
              resources:
                - managedconnectors
                - managedconnectors/status
                - managedconnectors/finalizers
                - managedconnectoroperators
                - managedconnectoroperators/status
                - managedconnectoroperators/finalizers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - secrets
                - configmaps
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - kafka.strimzi.io
              resources:
                - kafkaconnects
                - kafkaconnectors
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
                - get
                - list
                - watch
          serviceAccountName: cos-fleetshard-operator-debezium
      deployments:
        - name: cos-fleetshard-operator-debezium
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: cos-fleetshard-operator-debezium
                app.kubernetes.io/part-of: cos
                app.kubernetes.io/version: latest
            strategy: {}
            template:
              metadata:
                annotations:
                  prometheus.io/path: /q/metrics
                  prometheus.io/port: "8080"
                  prometheus.io/scheme: http
                  prometheus.io/scrape: "true"
                labels:
                  app.kubernetes.io/name: cos-fleetshard-operator-debezium
                  app.kubernetes.io/part-of: cos
                  app.kubernetes.io/version: latest
              spec:
                containers:
                  - env:
                      - name: KUBERNETES_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: SMALLRYE_CONFIG_LOCATIONS
                        value: /mnt/app-config/configuration
                      - name: OVERRIDE_PROPERTIES_LOCATION
                        value: /mnt/app-config/override/override.properties
                      - name: COS_OPERATOR_ID
                        value: cos-fleetshard-operator-debezium
                      - name: COS_OPERATOR_VERSION
                        value: 1.5.0
                    image: quay.io/rhoas/cos-fleetshard-operator-debezium@sha256:d94225bd990f9ae689b797bf04366ec1ffabb70a15166ea41f466f8cb771913c
                    imagePullPolicy: IfNotPresent
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /q/health/live
                        port: 8080
                        scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 10
                    name: cos-fleetshard-operator-debezium
                    ports:
                      - containerPort: 8080
                        name: http
                        protocol: TCP
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /q/health/ready
                        port: 8080
                        scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 10
                    resources:
                      limits:
                        cpu: "1"
                        memory: 512Mi
                      requests:
                        cpu: 500m
                        memory: 512Mi
                    volumeMounts:
                      - mountPath: /mnt/app-config/configuration
                        name: app-config
                      - mountPath: /mnt/app-config/override
                        name: app-config-override
                imagePullSecrets:
                  - name: addon-pullsecret
                serviceAccountName: cos-fleetshard-operator-debezium
                volumes:
                  - configMap:
                      defaultMode: 420
                      name: cos-fleetshard-operator-debezium-config
                      optional: false
                    name: app-config
                  - configMap:
                      defaultMode: 420
                      name: cos-fleetshard-operator-debezium-config-override
                      optional: true
                    name: app-config-override
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  maintainers:
    - email: mas-connectors@redhat.com
      name: Red Hat OpenShift Connectors team <mas-connectors@redhat.com>
  maturity: alpha
  provider:
    name: Red Hat
  version: 1.1.20
  replaces: cos-fleetshard-operator-debezium.
