apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    repository: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard/tree/main/cos-fleetshard-sync
  name: cos-fleetshard-sync.v1.1.1
spec:
  description: The cos-fleetshard-sync is responsible for synchronizing data with the control plane and creating/updating/deleting ManagedConnectors in the data plane.
  displayName: cos-fleetshard-sync
  maintainers:
    - name: Red Hat OpenShift Connectors team <mas-connectors@redhat.com>
      email: mas-connectors@redhat.com
  maturity: alpha
  provider:
    name: Red Hat
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: false
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: true
  install:
    strategy: deployment