resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.20-test1
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:d9527b374ef70585f0a6856df94c9d71182b46120b8922c732e104448fb38ba3
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
