resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.23
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:6ced745dff53f77adcae998b540751ff47c60ffa875da7bfca5ba658cf95abc0
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
