resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.21
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:f1934557148699c402391f94d2de87ac84a525ae8609b1b540f7aed5a42a75c5
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
