resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.21
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:e68d857baf0c2db4ead725bf29779231057ad73e01e2bf188c7ba40f2b58ad01
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
