resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.16
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:20240e70b5519b093012764196b20e6e7f2e9edd4f9ac01b58497c476abb4cdd
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
