resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.10
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:3fb69c74b6e655716133592c7037f31c4dde3e2120ff53345dbd2ded251f4d6c
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
