resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.26
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:0ba61c67c2edca7ddf47e0d1f928854548ac5a8dd5e8f104849f3030ab072423
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
