resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.11
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:7b9a447068b5867ee1dbf4f0465898ef924aebb309438ceeb9b54b2b51c7680d
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
