resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.14
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:5c34744b3ee4b6562cc2b3f79ea8f4469678c3d9a637355efb56066f41cb3531
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
