resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.28
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:aa109f0b625a4df418b1ab3d5d0f72e936a865b52bad54990560b0b698691ef4
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
