resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.12
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:58d0a1a2899f860037c6b2d6132f9ac603ec870c555662c68e5e0014ee4836ae
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
