resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.13
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:dd8447335a2be60ad1cee16f29f96d0eae6e3a8a1dac2e52206ac59c61467bea
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
