resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.27
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: sha256:833f56e771a537842d8d470c79a8b37291ef4ec2155b6ede60825f35678eb867
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
