apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: strimzi-kafka-operator.v0.0.11
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: KafkaBridge
        name: kafkabridges.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaConnector
        name: kafkaconnectors.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaConnect
        name: kafkaconnects.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaMirrorMaker2
        name: kafkamirrormaker2s.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaMirrorMaker
        name: kafkamirrormakers.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaRebalance
        name: kafkarebalances.kafka.strimzi.io
        version: v1beta2
      - kind: Kafka
        name: kafkas.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaTopic
        name: kafkatopics.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaTopic
        name: kafkatopics.kafka.strimzi.io
        version: v1beta1
      - kind: KafkaTopic
        name: kafkatopics.kafka.strimzi.io
        version: v1alpha1
      - kind: KafkaUser
        name: kafkausers.kafka.strimzi.io
        version: v1beta2
      - kind: KafkaUser
        name: kafkausers.kafka.strimzi.io
        version: v1beta1
      - kind: KafkaUser
        name: kafkausers.kafka.strimzi.io
        version: v1alpha1
      - kind: StrimziPodSet
        name: strimzipodsets.core.strimzi.io
        version: v1beta2
  description: Strimzi Kafka Operator description. TODO.
  displayName: Strimzi Kafka Operator
  icon: []
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - storage.k8s.io
              resources:
                - storageclasses
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - list
            - apiGroups:
                - kafka.strimzi.io
              resources:
                - kafkatopics
                - kafkatopics/status
                - kafkausers
                - kafkausers/status
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - get
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - pods
                - serviceaccounts
                - configmaps
                - services
                - endpoints
                - secrets
                - persistentvolumeclaims
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - kafka.strimzi.io
              resources:
                - kafkas
                - kafkas/status
                - kafkaconnects
                - kafkaconnects/status
                - kafkaconnectors
                - kafkaconnectors/status
                - kafkamirrormakers
                - kafkamirrormakers/status
                - kafkabridges
                - kafkabridges/status
                - kafkamirrormaker2s
                - kafkamirrormaker2s/status
                - kafkarebalances
                - kafkarebalances/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - core.strimzi.io
              resources:
                - strimzipodsets
                - strimzipodsets/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - extensions
              resources:
                - deployments
                - deployments/scale
                - replicasets
                - replicationcontrollers
                - networkpolicies
                - ingresses
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - deployments
                - deployments/scale
                - deployments/status
                - statefulsets
                - replicasets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - build.openshift.io
              resources:
                - buildconfigs
                - buildconfigs/instantiate
                - builds
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - networking.k8s.io
              resources:
                - networkpolicies
                - ingresses
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
                - routes/custom-host
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
          serviceAccountName: strimzi-cluster-operator
      deployments:
        - name: strimzi-cluster-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: strimzi
                name: strimzi-cluster-operator
                strimzi.io/kind: cluster-operator
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: strimzi
                  name: strimzi-cluster-operator
                  strimzi.io/kind: cluster-operator
              spec:
                containers:
                  - args:
                      - /opt/strimzi/bin/cluster_operator_run.sh
                    env:
                      - name: STRIMZI_NAMESPACE
                        value: '*'
                      - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
                        value: "120000"
                      - name: STRIMZI_OPERATION_TIMEOUT_MS
                        value: "300000"
                      - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
                        value: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
                        value: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
                        value: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
                        value: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_KAFKA_IMAGES
                        value: |
                          3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
                          3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_KAFKA_CONNECT_IMAGES
                        value: |
                          3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
                          3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
                        value: |
                          3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
                          3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
                        value: |
                          3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
                          3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
                      - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
                        value: quay.io/strimzi/operator:0.28.0
                      - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
                        value: quay.io/strimzi/operator:0.28.0
                      - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
                        value: quay.io/strimzi/operator:0.28.0
                      - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
                        value: quay.io/strimzi/kafka-bridge:0.21.4
                      - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
                        value: quay.io/strimzi/jmxtrans:0.28.0
                      - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
                        value: quay.io/strimzi/kaniko-executor:0.28.0
                      - name: STRIMZI_DEFAULT_MAVEN_BUILDER
                        value: quay.io/strimzi/maven-builder:0.28.0
                      - name: STRIMZI_OPERATOR_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: STRIMZI_FEATURE_GATES
                    image: quay.io/strimzi/operator:0.28.0
                    livenessProbe:
                      httpGet:
                        path: /healthy
                        port: http
                      initialDelaySeconds: 10
                      periodSeconds: 30
                    name: strimzi-cluster-operator
                    ports:
                      - containerPort: 8080
                        name: http
                    readinessProbe:
                      httpGet:
                        path: /ready
                        port: http
                      initialDelaySeconds: 10
                      periodSeconds: 30
                    resources:
                      limits:
                        cpu: "1"
                        memory: 384Mi
                      requests:
                        cpu: 200m
                        memory: 384Mi
                    volumeMounts:
                      - mountPath: /tmp
                        name: strimzi-tmp
                      - mountPath: /opt/strimzi/custom-config/
                        name: co-config-volume
                serviceAccountName: strimzi-cluster-operator
                volumes:
                  - emptyDir:
                      medium: Memory
                      sizeLimit: 1Mi
                    name: strimzi-tmp
                  - configMap:
                      name: strimzi-cluster-operator
                    name: co-config-volume
      permissions:
        - rules:
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - pods
                - serviceaccounts
                - configmaps
                - services
                - endpoints
                - secrets
                - persistentvolumeclaims
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - kafka.strimzi.io
              resources:
                - kafkas
                - kafkas/status
                - kafkaconnects
                - kafkaconnects/status
                - kafkaconnectors
                - kafkaconnectors/status
                - kafkamirrormakers
                - kafkamirrormakers/status
                - kafkabridges
                - kafkabridges/status
                - kafkamirrormaker2s
                - kafkamirrormaker2s/status
                - kafkarebalances
                - kafkarebalances/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - core.strimzi.io
              resources:
                - strimzipodsets
                - strimzipodsets/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - extensions
              resources:
                - deployments
                - deployments/scale
                - replicasets
                - replicationcontrollers
                - networkpolicies
                - ingresses
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - deployments
                - deployments/scale
                - deployments/status
                - statefulsets
                - replicasets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - build.openshift.io
              resources:
                - buildconfigs
                - buildconfigs/instantiate
                - builds
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - networking.k8s.io
              resources:
                - networkpolicies
                - ingresses
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
                - routes/custom-host
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
            - apiGroups:
                - kafka.strimzi.io
              resources:
                - kafkatopics
                - kafkatopics/status
                - kafkausers
                - kafkausers/status
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - patch
                - update
          serviceAccountName: strimzi-cluster-operator
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - strimzi-kafka-operator
  links:
    - name: Strimzi Kafka Operator
      url: https://strimzi-kafka-operator.domain
  maintainers:
    - email: your@email.com
      name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.11
