apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "camel.apache.org/v1",
          "kind": "IntegrationPlatform",
          "metadata": {
            "name": "camel-k"
          }
        }
      ]
    capabilities: Full Lifecycle
    categories: Integration & Delivery
    certified: "false"
    description: Apache Camel K is a lightweight integration platform, born on Kubernetes, with serverless superpowers.
    operators.operatorframework.io/internal-objects: '["builds.camel.apache.org","integrationkits.camel.apache.org","camelcatalogs.camel.apache.org"]'
    repository: https://github.com/apache/camel-k
    support: Camel
    cos.bf2.org/underlying-version: 1.10.1
    olm.skipRange: '>=1.1.6 <1.1.22'
  name: camel-k-operator.v1.1.22
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Build
        name: builds.camel.apache.org
        version: v1
      - kind: CamelCatalog
        name: camelcatalogs.camel.apache.org
        version: v1
      - kind: IntegrationKit
        name: integrationkits.camel.apache.org
        version: v1
      - kind: IntegrationPlatform
        name: integrationplatforms.camel.apache.org
        version: v1
      - kind: Integration
        name: integrations.camel.apache.org
        version: v1
      - kind: KameletBinding
        name: kameletbindings.camel.apache.org
        version: v1alpha1
      - kind: Kamelet
        name: kamelets.camel.apache.org
        version: v1alpha1
  description: |
    Apache Camel K
    ==============

    Apache Camel K is a lightweight integration platform, born on Kubernetes, with serverless superpowers.

    ## Installation

    To start using Camel K, install the operator and then create the following `IntegrationPlatform`:
    ```
    apiVersion: camel.apache.org/v1
    kind: IntegrationPlatform
    metadata:
      name: camel-k
      labels:
        app: "camel-k"
    ```

    An `IntegrationPlatform` resource is automatically created by default on OpenShift, so you can skip this step.
    Also, You can edit the `IntegrationPlatform`, to configure Camel K.
    The configuration from the `IntegrationPlatform` will apply to the Camel integrations created in the same namespace/project.

    ## Running an Integration

    After the initial setup, you can run a Camel integration on the cluster by creating an example `Integration`, e.g.:
    ```
    apiVersion: camel.apache.org/v1
    kind: Integration
    metadata:
      name: example
    spec:
      sources:
      - name: Example.java
        content: |
          import org.apache.camel.builder.RouteBuilder;

          public class Example extends RouteBuilder {
              @Override
              public void configure() throws Exception {
                  from("timer:tick")
                      .setBody(constant("Hello World!"))
                  .to("log:info?skipBodyLineSeparator=false");
              }
          }
    ```
  displayName: Camel K Operator
  icon: []
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resourceNames:
                - local-registry-hosting
              resources:
                - configmaps
              verbs:
                - get
            - apiGroups:
                - camel.apache.org
              resources:
                - builds
                - camelcatalogs
                - integrationkits
                - integrationplatforms
                - integrations
                - kameletbindings
                - kamelets
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - camel.apache.org
              resources:
                - builds
              verbs:
                - delete
            - apiGroups:
                - camel.apache.org
              resources:
                - builds/status
                - camelcatalogs/status
                - integrationkits/status
                - integrationplatforms/status
                - integrations/scale
                - integrations/status
                - kameletbindings/status
                - kameletbindings/scale
                - kamelets/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - configmaps
                - secrets
                - serviceaccounts
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - pods/proxy
              verbs:
                - get
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - create
                - delete
                - get
                - update
                - list
                - patch
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
                - clusterrolebindings
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - cronjobs
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resourceNames:
                - addressable-resolver
              resources:
                - clusterroles
              verbs:
                - bind
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
                - get
                - list
                - watch
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - camel.apache.org
              resources:
                - builds/finalizers
                - integrationkits/finalizers
                - integrationplatforms/finalizers
                - integrations/finalizers
                - kameletbindings/finalizers
              verbs:
                - update
            - apiGroups:
                - ""
                - build.openshift.io
              resources:
                - buildconfigs
                - buildconfigs/webhooks
                - builds
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
                - image.openshift.io
              resources:
                - imagestreamimages
                - imagestreammappings
                - imagestreams
                - imagestreams/secrets
                - imagestreamtags
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
                - build.openshift.io
              resources:
                - buildconfigs/instantiate
                - buildconfigs/instantiatebinary
                - builds/clone
              verbs:
                - create
            - apiGroups:
                - ""
                - route.openshift.io
              resources:
                - routes
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
                - route.openshift.io
              resources:
                - routes/custom-host
              verbs:
                - create
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - podmonitors
              verbs:
                - create
                - delete
                - deletecollection
                - get
                - list
                - patch
                - update
                - watch
          serviceAccountName: camel-k-operator
      deployments:
        - name: camel-k-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: camel-k
                name: camel-k-operator
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: camel-k
                  app.kubernetes.io/component: operator
                  app.kubernetes.io/name: camel-k
                  app.kubernetes.io/version: 1.10.4-SNAPSHOT
                  camel.apache.org/component: operator
                  name: camel-k-operator
              spec:
                containers:
                  - command:
                      - kamel
                      - operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: KAMEL_INSTALL_DEFAULT_KAMELETS
                        value: "false"
                      - name: LOG_LEVEL
                        valueFrom:
                          configMapKeyRef:
                            key: log.level
                            name: camel-k-override-config
                            optional: true
                      - name: OPERATOR_NAME
                        value: camel-k
                      - name: OPERATOR_ID
                        value: camel-k
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                    image: docker.io/apache/camel-k@sha256:45b5d4e32c3eb9231fc0c0870039c2966d6332260e096fa097b0076e51938159
                    imagePullPolicy: IfNotPresent
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 20
                      periodSeconds: 10
                    name: camel-k-operator
                    ports:
                      - containerPort: 8080
                        name: metrics
                    resources:
                      limits:
                        cpu: "1"
                        memory: 256Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                serviceAccountName: camel-k-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - apache
    - kamel
    - kubernetes
    - serverless
    - microservices
  labels:
    name: camel-k-operator
  links:
    - name: Camel K source code repository
      url: https://github.com/apache/camel-k
  maintainers:
    - email: users@camel.apache.org
      name: The Apache Software Foundation
  maturity: alpha
  minKubeVersion: 1.11.0
  provider:
    name: The Apache Software Foundation
  selector:
    matchLabels:
      name: camel-k-operator
  version: 1.1.22
  replaces: camel-k-operator.v1.1.21
