FROM registry.access.redhat.com/ubi8/ubi-minimal

COPY cos-fleet-catalog-camel /etc/connectors

LABEL name="cos-fleet-catalog-camel" \
    vendor="Red Hat" \
    summary="CosFleetCatalogCamel" \
    description="Kafka Connector Service Catalog Camel"
