resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.23
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:5f02d503b2688e03093df523a24467f197d550cb8c1481b7bf096e5048187137
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
