resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.14
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:27ba2a35aa865a8aec36ed2857de5e86dec6c2495f52d16c559c0889bdd2b1da
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
