resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.15
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:d59d330dd42a6e4bc469427aed1cc2b7e458a4de56ae81b2a6867b4b06bbf484
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
