resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.20
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:18c0af4c8ce9d200532161b38316864535e594b08d6545c44a0aa78bbab2fa23
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
