resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.22
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:bdc106a110801ef6cfca31e475aa771b1864e76d7c021f9db2abdb5e6de6ca99
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
