resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.28
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:67d4f6720fdfa3d3f87289f81f059548c4cc2182064cea5904e1664d5236ec10
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
