resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.19
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:c6fd70145a3d1aff8dfefc89c5353c709d3b35ff0826aba16e5d57f49b955ddd
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
