resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.13
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:5920dd21495835af82fd6f50f15d3a17578037bd2d7bd34659889a817cd68685
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
