resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.21
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:7cb7cc8bba20833d9d431d314aa1151e5f4ce6fddbfb2386cf02a1944c813aab
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
