resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.17
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:30c0e3295a6a26174bd0b094f325c6639491dd0865ab76df40311e5d0e17a505
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
