resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.27
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:6036efc444bcccbaf3132b069aaeabd23f485162fdb6558bcc4d1d37ffc35fe2
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
