resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.29
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:3f8b67b877f0b76611e3fc9cc7d922e7ba588c94033b5a5bb1437973a7e5f367
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
