resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.7
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: v1.1.7-5d110ac416b892a426a0cb716b74e171b66411a6

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cos-fleetshard-sync
  spec:
    template:
      spec:
        imagePullSecrets:
          - name: addon-pullsecret
