resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/?ref=v1.1.11
images:
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: sha256:2fb365c32267eac023954f7f6f5386266aaca5f03d550374c5ecb32ec61e44af
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-sync
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
