resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: main-0307ec6cf6d6c0daef0021782859a73004b18143
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: main-0307ec6cf6d6c0daef0021782859a73004b18143
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: main-0307ec6cf6d6c0daef0021782859a73004b18143
