resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: ""
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: ""
  - name: quay.io/rhoas/cos-fleetshard-sync
    digest: ""
  - name: quay.io/rhoas/cos-camel-k
    digest: sha256:f42213014a5a5164abddb71984b24864e3b73044df2ab94ce76f5aec42b2864c
  - name: quay.io/strimzi/operator
    digest: sha256:8b010c5fb8244b742a37f264feefc116d75bb2abd2d6895375cbeea250727b39
