resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: main-1f9bb2a5119267a633d1f671d163886d09da3f2d
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: main-1f9bb2a5119267a633d1f671d163886d09da3f2d
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: main-1f9bb2a5119267a633d1f671d163886d09da3f2d
