resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: main-e74bec3588daa979e1ca2f3d81ad34f7df48ec1d
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: main-e74bec3588daa979e1ca2f3d81ad34f7df48ec1d
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: main-e74bec3588daa979e1ca2f3d81ad34f7df48ec1d
