resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: main-0f6b51d083363715b255cd825de90122118d00c6
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: main-0f6b51d083363715b255cd825de90122118d00c6
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: main-0f6b51d083363715b255cd825de90122118d00c6
