resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: main-2a65d33dd91153a05099bc6476af6c3de1ba0394
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: main-2a65d33dd91153a05099bc6476af6c3de1ba0394
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: main-2a65d33dd91153a05099bc6476af6c3de1ba0394
