resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/dev
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    newTag: main-acc0eb2559f9580676fedc10000459111734cb82
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: main-acc0eb2559f9580676fedc10000459111734cb82
  - name: quay.io/rhoas/cos-fleetshard-sync
    newTag: main-acc0eb2559f9580676fedc10000459111734cb82
