name: Build Tag

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "LICENSE"
      - "**/.gitignore"
      - "**.md"
      - "**.adoc"
      - "*.txt"
      - "etc/kubernetes/manifests/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name}}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  DEPLOY_TAG: ${{ github.ref_name}}

jobs:
  bundles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overlay:
          - "staging"
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "github"
          skip_cache: "true"
          kustomize: "latest"
          operator-sdk: "1.17.0"
          yq: "latest"
      - name: "Build bundles for ${{ matrix.overlay }}"
        env:
          ADDON_OVERLAY: ${{ matrix.overlay }}
        run: |
          export ADDON_VERSION="${DEPLOY_TAG#v}"

          rm -rf addons

          make bundles

      - name: "Create PR for ${{ matrix.overlay }}"
        env:
          ADDON_OVERLAY: ${{ matrix.overlay }}
          BRANCH_NAME: addon.${{ matrix.overlay }}-${{ env.DEPLOY_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export ADDON_VERSION="${DEPLOY_TAG#v}"

          echo ""
          echo "tag     : $DEPLOY_TAG"
          echo "branch  : $BRANCH_NAME"
          echo "version : $ADDON_VERSION"
          echo "overlay : $ADDON_OVERLAY"
          echo ""

          git config user.email "mas-connectors@redhat.com" 
          git config user.name "mas-connectors"

          git checkout -b ${BRANCH_NAME}
          git add ./addons
          git commit -m "Generate bundle ${{ env.ADDON_VERSION }}" ./addons
          git reset --hard
          git push -u origin ${BRANCH_NAME}

          # GH CLI can't find the branch on remote... needs some time :)
          sleep 15

          gh config set prompt disabled

          gh pr create \
            --fill \
            --base main \
            --title "Generate bundle $ADDON_VERSION" \
            --body "sha ${{ github.sha }}, overlay ${{ matrix.overlay }}, tag: ${DEPLOY_TAG}, bundle : ${DEPLOY_TAG} "
