name: Deploy Catalog

on:
  push:
    branches:
      - main
    paths:
      - "kustomize/overlays/dev/control-plane/cos-fleet-catalog-camel/kustomization.yaml"
      - "kustomize/overlays/dev/control-plane/cos-fleet-catalog-debezium/kustomization.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name}}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  CONNECTORS_DIR: connectors

jobs:
  deploy-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          skip_cache: "true"
          oc: "latest"
      - name: Log in and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.K8S_CLUSTER_DEV }}
          openshift_token: ${{ secrets.K8S_CLUSTER_DEV_TOKEN }}
          insecure_skip_tls_verify: false
          namespace: ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}
      - name: Deploy Catalog
        run: |
          kubectl replace -k "${CONNECTORS_DIR}" -n ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}

  restart-fleet-manager:
    runs-on: ubuntu-latest
    needs: deploy-catalog
    steps:
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          skip_cache: "true"
          oc: "latest"
      - name: Log in and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.K8S_CLUSTER_DEV }}
          openshift_token: ${{ secrets.K8S_CLUSTER_DEV_TOKEN }}
          insecure_skip_tls_verify: false
          namespace: ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}
      - name: Restart FleetManager
        run: |
          oc rollout restart deployment/cos-fleet-manager --namespace ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}
