resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.10
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: ""
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
