resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.13
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:3798ecedad6ee40440870ef7da60af170791bce60ee1e5649f1dadf26df83a08
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
