resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.20
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:d94225bd990f9ae689b797bf04366ec1ffabb70a15166ea41f466f8cb771913c
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
