resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.7
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    newTag: v1.1.7-5d110ac416b892a426a0cb716b74e171b66411a6
