resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.30
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:dae792aa583433cdb58cb93294b93a393ad22212140243bbb4fbc526cbf183e5
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
