resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.18
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:7fc7515f1eb6afe6a9dc7781033d32532d47960c304678b747995e2cc2f7d420
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
