resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.20-test1
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:1601fd1ecb9a0ba803336afbf3d77fed6203c67d0685ec237f72ae9abd9b4418
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
