resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.21
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:9b2a0309a3ac1523a0edc2f5a01090d1453745c47633d0047165f591f53d2fa4
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
