resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.25
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:18800d706c8c139faf3bca1a66c88d9ff557fab7e921a8f5a0ed0c331752c51c
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
