resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.27
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:d40b60d1eb0445f86c9a9f94564133a16bc6cbf3cf8efef496d064a41e71a1c8
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
