resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.16
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:30f0004444fad7f714cac712dd5d6101c950520b8ee15e68e5a793f16b0931fa
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
