resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.14
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:7cc19a4453a1f3aca23de8e706bcad6a54df0698c26e09afe930059ffa83bc93
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
