resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.15
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:0c2abc762e653f4c3b858e41df8d5c071dd9dbfc6c89131d4f68326789abcdcc
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
