resources:
  - https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/?ref=v1.1.23
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-debezium
    digest: sha256:49596e29f56a7fdae6703b11e3a74777127606320c9b352fc73d63da33d55d9f
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-debezium
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
